CREATE TABLE users_train (
        FECHA_DATO date,
        NCODPERS character varying(8),
        IND_EMPLEADO character varying(1),
        PAIS_RESIDENCIA character varying(2),
        SEXO character varying(2),
        AGE int,
        FECHA_ALTA date,
        IND_NUEVO boolean,
        ANTIGUEDAD int,
        INDREL character varying(2),
        ULT_FEC_CLI_1T date,
        INDREL_1MES character varying(1),
        TIPREL_1MES character varying(1),
        INDRESI boolean,
        INDEXT boolean,
        CONYUEMP boolean,
        CANAL_ENTRADA character(3),
        INDFALL boolean,
        TIPODOM character varying(1),
        COD_PROV character varying(2),
        NOMPROV character varying(100),
        IND_ACTIVIDAD_CLIENTE boolean,
        RENTA money,
        SEGMENTO character varying(2),
        IND_AHOR_FIN_ULT1 character varying(20),
        IND_AVAL_FIN_ULT1 boolean,
        IND_CCO_FIN_ULT1  character varying(1),
        IND_CDER_FIN_ULT1 boolean,
        IND_CNO_FIN_ULT1 boolean,
        IND_CTJU_FIN_ULT1 boolean,
        IND_CTMA_FIN_ULT1 boolean,
        IND_CTOP_FIN_ULT1 boolean,
        IND_CTPP_FIN_ULT1 boolean,
        IND_DECO_FIN_ULT1 boolean,
        IND_DEME_FIN_ULT1 boolean,
        IND_DELA_FIN_ULT1 boolean,
        IND_ECUE_FIN_ULT1 boolean,
        IND_FOND_FIN_ULT1 boolean,
        IND_HIP_FIN_ULT1 boolean,
        IND_PLAN_FIN_ULT1 boolean,
        IND_PRES_FIN_ULT1 boolean,
        IND_RECA_FIN_ULT1 boolean,
        IND_TJCR_FIN_ULT1 boolean,
        IND_VALO_FIN_ULT1 boolean,
        IND_VIV_FIN_ULT1 boolean,
        IND_NOMINA_ULT1 boolean,
        IND_NOM_PENS_ULT1 boolean,
        IND_RECIBO_ULT1 boolean
        );
